set up CI

diff --git a/Firmware/unit_tests/run b/Firmware/unit_tests/run
--- a/Firmware/unit_tests/run
+++ b/Firmware/unit_tests/run
@@ -3,9 +3,12 @@
 # Run unit tests
 
 print_usage() {
-    echo "Usage:
-  -m flag specifies, that only tests, affected by recent changes shall be ran
-  -n flag specifies, that if build.ninja file is not found in test_path directory, the script shouldn't regenerate it"
+    echo "Input flag usage:
+  -m only tests, affected by recent changes are to be ran
+  -n if build.ninja file is not found in test_path directory, the script shouldn't regenerate it
+  -c generate coverage report
+  -o open coverage report in browser after generating it
+  -g monochrome output"
 }
 
 readonly WORKING_DIR=$pwd
@@ -16,23 +19,33 @@ readonly BROWSER='xdg-open'
 
 readonly BUILD_FILENAME=build.ninja
 
-readonly RED='\033[0;31m'
-readonly GREEN='\033[0;32m'
-readonly NC='\033[0m' # No Color
-
 modified_flag=false
 no_generation_flag=false
 coverage_flag=false
+open_coverage_report_flag=false
+no_color_flag=false
 
-while getopts 'mnc' flag; do
+while getopts 'mncog' flag; do
     case "${flag}" in
         m) modified_flag=true ;;
         n) no_generation_flag=true ;;
         c) coverage_flag=true ;;
+        o) open_coverage_report_flag=true ;;
+        g) no_color_flag=true ;;
         *) print_usage
             exit 1 ;;
     esac
 done
+
+if [[ "${no_color_flag}" = true ]]; then
+    readonly RED=''
+    readonly GREEN=''
+    readonly NC=''
+else
+    readonly RED='\033[0;31m'
+    readonly GREEN='\033[0;32m'
+    readonly NC='\033[0m' # No Color
+fi
 
 passed_tests=()
 failed_tests=()
@@ -93,6 +106,12 @@ elif [[ "${number_of_passed_tests}" = "${number_of_tests_ran}" ]]; then
     passed_str="all"
 fi
 
+exit_value=0 # no error
+if [[ "${number_of_failed_tests}" != "0" ]]; then
+    exit_value=1 # output non-zero value on exit
+fi
+
+
 echo "${number_of_tests_ran} unit tests were ran, ${passed_str} of them have passed."
 
 for test in ${passed_tests[*]}
@@ -118,9 +137,18 @@ if [[ "${coverage_flag}" = true ]]; then
         '/usr/include/*' '/usr/src/*' '*submodules/*' '*unit_tests/*' '*Interface.h' >/dev/null 2>&1
     genhtml coverage_filtered.info --output-directory . >/dev/null 2>&1
 
-    echo "Coverage report generated, it can be accessed at:"
-    echo "${UNIT_TESTS_DIR}/${COVERAGE_DIR_NAME}/index.html"
-    ${BROWSER} ${UNIT_TESTS_DIR}/${COVERAGE_DIR_NAME}/index.html
+    if [[ $? -ne 0 ]]; then
+        echo "Coverage report generation failed"
+    else
+        echo "Coverage report generated, it can be accessed at:"
+        echo "${UNIT_TESTS_DIR}/${COVERAGE_DIR_NAME}/index.html"
+
+        if [[ "${open_coverage_report_flag}" = true ]]; then
+            ${BROWSER} ${UNIT_TESTS_DIR}/${COVERAGE_DIR_NAME}/index.html
+        fi
+    fi
 fi
 
 cd ${WORKING_DIR}
+
+exit ${exit_value}
